apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain.api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: blockchain.api
  template:
    metadata:
      labels:
        name: blockchain.api
    spec:
      containers:
        - name: application
          image: "hasanshahjahan/blockchain-api:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000